/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#003543',
        'tertiary': '#8ee5be',
        'on-primary': '#002d6d',
        'outline': '#8c90a2',
        'surface-variant': '#2d3449',
        'primary-fixed': '#d9e2ff',
        'secondary-fixed': '#f0dbff',
        'on-secondary-container': '#d6a9ff',
        'outline-variant': '#424656',
        'surface-bright': '#31394d',
        'surface-container-high': '#222a3d',
        'on-secondary': '#490080',
        'secondary-fixed-dim': '#ddb7ff',
        'inverse-surface': '#dae2fd',
        'on-tertiary-container': '#e3f6ff',
        'tertiary-container': '#007995',
        'secondary': '#ddb7ff',
        'surface-dim': '#0b1326',
        'on-secondary-fixed-variant': '#6900b3',
        'surface-tint': '#afc6ff',
        'background': '#0b1326',
        'inverse-primary': '#0059c7',
        'surface-container-low': '#131b2e',
        'primary-fixed-dim': '#afc6ff',
        'secondary-container': '#6f00be',
        'primary': '#afc6ff',
        'error': '#ffb4ab',
        'primary-container': '#0068e8',
        'surface-container': '#171f33',
        'tertiary-fixed-dim': '#8ee5be',
        'inverse-on-surface': '#283044',
        'on-primary-container': '#f0f2ff',
        'surface-container-highest': '#2d3449',
        'on-background': '#dae2fd',
        'on-surface-variant': '#c2c6d9',
        'tertiary-fixed': '#b7eaff',
        'surface': '#0b1326',
        'surface-container-lowest': '#060e20',
        'on-surface': '#dae2fd',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-space-grotesk)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
